"""update users

Revision ID: 5f0fd2e2a873
Revises: 7b9a3b27e56e
Create Date: 2026-01-15 17:00:05.853649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f0fd2e2a873"
down_revision: Union[str, Sequence[str], None] = "7b9a3b27e56e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=150), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=150), nullable=False)
    )
    op.add_column(
        "users", sa.Column("password", sa.String(length=256), nullable=False)
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=254),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=254),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    op.drop_column("users", "password")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
