"""test db

Revision ID: e6b58d360e88
Revises:
Create Date: 2026-01-22 18:14:02.231318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6b58d360e88"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("measurement_unit", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("slug", name=op.f("uq_tags_slug")),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("avatar", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "recipes",
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("cooking_time", sa.Integer(), nullable=False),
        sa.Column(
            "pub_date",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author"], ["users.id"], name=op.f("fk_recipes_author_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
    )
    op.create_table(
        "subscriptions",
        sa.Column("subscriber_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_subscriber_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "subscriber_id", "author_id", name="unique_subscription"
        ),
    )
    op.create_table(
        "recipe_ingredient_association",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f(
                "fk_recipe_ingredient_association_ingredient_id_ingredients"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_ingredient_association_recipe_id_recipes"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_recipe_ingredient_association")
        ),
        sa.UniqueConstraint(
            "recipe_id", "ingredient_id", name="idx_unique_recipe_ingredient"
        ),
    )
    op.create_table(
        "recipe_tag_association",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_tag_association_recipe_id_recipes"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_recipe_tag_association_tag_id_tags"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_tag_association")),
        sa.UniqueConstraint(
            "recipe_id", "tag_id", name="idx_unique_recipe_tag"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_tag_association")
    op.drop_table("recipe_ingredient_association")
    op.drop_table("subscriptions")
    op.drop_table("recipes")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("ingredients")
    # ### end Alembic commands ###
