"""add recipe

Revision ID: b9bb26ea7622
Revises: 6c23915b75eb
Create Date: 2026-01-06 10:55:25.874024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9bb26ea7622"
down_revision: Union[str, Sequence[str], None] = "6c23915b75eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("cooking_time", sa.Integer(), nullable=False),
        sa.Column(
            "pub_date",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author"], ["users.id"], name=op.f("fk_recipes_author_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
    )
    op.create_table(
        "recipe_ingredient_association",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f(
                "fk_recipe_ingredient_association_ingredient_id_ingredients"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_ingredient_association_recipe_id_recipes"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_recipe_ingredient_association")
        ),
        sa.UniqueConstraint(
            "recipe_id", "ingredient_id", name="idx_unique_recipe_ingredient"
        ),
    )
    op.create_table(
        "recipe_tag_association",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_tag_association_recipe_id_recipes"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_recipe_tag_association_tag_id_tags"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_tag_association")),
        sa.UniqueConstraint(
            "recipe_id", "tag_id", name="idx_unique_recipe_tag"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_tag_association")
    op.drop_table("recipe_ingredient_association")
    op.drop_table("recipes")
    # ### end Alembic commands ###
